### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by RadicalOyster** [suomalainenmari/ot-harjoitustyo2021#1]
## Kommentit
* Projektin rakenne on selkeä.
* Muuttujat ja metodit on nimetty hyvin ja metodit sopivan lyhyitä.
* Koodi on kompaktia ja luettavaa.
* Käyttöliittymä on toimiva, mutta hieman tönkkö.
 * Tulos ei erotu visuaalisesti
muista käyttöliittymän elementeistä eikä sen sijoittelukaan varsinaisesti kohdista
huomiota itseensä.
   * Tuloksen voisi asettaa jonnekin korkeammalle ja lähemmäksi syötettä.
 * Jokainen muistiinpano leventää ikkunnaa ja näkymässä on pystysuorassa paljon
 tyjää tilaa.
   * Jokainen muistiinpano voisi olla omalla rivillään ja ikkunan kasvamisen
   estämiseksi, voisi muistiinpanoille mahdollisesti olla vierityspalkki jos
   muistiinpanojen määrä kasvaa liian suureksi.
 * Muistiinpanolista kasvaa nyt vaikka muistiinpanon sisältö olisi tyhjä.
 * Muistiinpanokenttä voisi myös olla hyvä nollata muistiinpanon lisäämisen
 jälkeen jottei samaa muistiinpanoa vahingossa tule lisätyksi useaan kertaan.

## Muita ehdotuksia

Käyttäjän kannalta voisi myös olla mukava nähdä tähän asti ketjutetut kommenot
tai ainakin viimeisin laskutoimitus.
Esim. jos laskimeen kirjoittaa 15 + 5, voisi tuloksen lisäksi jossain syötteen tienoilla
myös näkyä tuo 15 + 5, vaikkapa esittämällä tuloksen muodossa 15 + 5 = 20.

**Comment by suomalainenmari** [comment]
Hei, kiitos kommenteista. Järkeviä pointteja. Osa näistä olikin tarkoitus vielä korjata/toteuttaa. Laitetaan loput pohdintaan. Tsemppiä myös sinne loppurutistukseen!
